name: CI

on:
  push:
    branches: [ci-test]
  pull_request:
    branches: [ci-test]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: '11.x'
      - run: yarn install
      - run: yarn test
